services:
  postgres:
    image: postgres:16
    container_name: studio_postgres
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  etl:
    build: ./etl
    container_name: studio_etl
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - ./data:/data

  metabase:
    image: metabase/metabase:v0.58.5.x
    container_name: studio_metabase
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB}
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    volumes:
      - metabase-data:/metabase-data

volumes:
  pgdata:
  metabase-data:
